CLASSIC_CALENDAR_L = {}

local L = CLASSIC_CALENDAR_L

L.Options = {
	["enUS"] = {
		["PVPArtText"] 					 = "Show calendar art for PVP weekends",
		["ChildrensWeekText"] 			 = "Show calendar art for Childrens Week",
		["FireworksSpectacularText"] 	 = "Show calendar art for Fireworks Spectacular",
		["CALENDAR_FILTER_BATTLEGROUND"] = "Battleground Call to Arms",
	},
	["frFR"] = {
		["PVPArtText"] 					 = "",
		["ChildrensWeekText"] 			 = "",
		["FireworksSpectacularText"] 	 = "",
		["CALENDAR_FILTER_BATTLEGROUND"] = "Appel aux armes de champ de bataille",

	},
	["esMX"] = {
		["PVPArtText"] 					 = "",
		["ChildrensWeekText"] 			 = "",
		["FireworksSpectacularText"] 	 = "",
		["CALENDAR_FILTER_BATTLEGROUND"] = "Llamamiento a las armas de campo de batalla",
	},
	["esES"] = {
		["PVPArtText"] 					 = "",
		["ChildrensWeekText"] 			 = "",
		["FireworksSpectacularText"] 	 = "",
		["CALENDAR_FILTER_BATTLEGROUND"] = "Llamamiento a las armas de campo de batalla",
	},
	["ptBR"] = {
		["PVPArtText"] 					 = "",
		["ChildrensWeekText"] 			 = "",
		["FireworksSpectacularText"] 	 = "",
		["CALENDAR_FILTER_BATTLEGROUND"] = "Chamado às Armas em Campo de Batalha",
	},
	["deDE"] = {
		["PVPArtText"] 					 = "",
		["ChildrensWeekText"] 			 = "",
		["FireworksSpectacularText"] 	 = "",
		["CALENDAR_FILTER_BATTLEGROUND"] = "Schlachtfeldtag",
	},
	["ruRU"] = {
		["PVPArtText"] 					 = "",
		["ChildrensWeekText"] 			 = "",
		["FireworksSpectacularText"]	 = "",
		["CALENDAR_FILTER_BATTLEGROUND"] = "PvP-потасовки",
	},
	["koKR"] = {
		["PVPArtText"] 				 	 = "",
		["ChildrensWeekText"] 			 = "",
		["FireworksSpectacularText"] 	 = "",
		["CALENDAR_FILTER_BATTLEGROUND"] = "전장으로 전장",
	},
	["zhTW"] = {
		["PVPArtText"] 					 = "",
		["ChildrensWeekText"] 			 = "",
		["FireworksSpectacularText"]	 = "",
		["CALENDAR_FILTER_BATTLEGROUND"] = "戰場戰鬥的號角",
	},
	["zhCN"] = {
		["PVPArtText"] 					 = "",
		["ChildrensWeekText"] 			 = "",
		["FireworksSpectacularText"]	 = "",
		["CALENDAR_FILTER_BATTLEGROUND"] = "战场的召唤",
	},
}
-- The following is auto-generated by the addon found at Belarr/CalendarDumper

L.Localization = {
	["ptBR"] = {
		["CalendarPVP"] = {
			["ArathiBasin"] = {
				["name"] = "Chamado às Armas: Bacia Arathi",
				["description"] = "A batalha pela Bacia Arathi se intensifica.  Grande honra é concedida aos que devotam armas aos soberanos e lutam em Arathi.",
			},
			["AlteracValley"] = {
				["name"] = "Chamado às Armas: Vale Alterac",
				["description"] = "A batalha pelo Vale Alterac se intensifica.  Grande honra é concedida aos que devotam armas aos soberanos e lutam em Alterac.",
			},
			["WarsongGulch"] = {
				["name"] = "Chamado às Armas: Ravina Brado Guerreiro",
				["description"] = "A batalha pela Ravina Brado Guerreiro se intensifica.  Grande honra é concedida aos que devotam armas aos soberanos e lutam na Ravina.",
			},
		},
		["CalendarHolidays"] = {
			["DarkmoonFaireMulgore"] = {
				["name"] = "Feira de Negraluna",
				["description"] = "A Feira de Negraluna chegou e, dessa vez, o evento acontecerá no sopé do Penhasco do Trovão.\r\n\r\nVenha ver Silas Negraluna e sua trupe, divirta-se com jogos que testam a mente e os nervos e veja maravilhas exóticas vindas de todas as partes de Azeroth... e além!",
			},
			["HarvestFestival"] = {
				["name"] = "Festival da Colheita",
				["description"] = "O Festival da Colheita é a época de lembrar dos que sacrificaram a vida para ajudar amigos e aliados.  Festas são realizadas fora de Orgrimmar e Altaforja para honrar os heróis caídos.",
			},
			["FireworksSpectacular"] = {
				["name"] = "Espetáculo de Fogos de Artifício",
				["description"] = "Depois do pôr do sol, o final do Solstício é celebrado de hora em hora com uma grande queima de fogos de artifício.\r\n\r\nPara assistir ao espetáculo, visite qualquer capital ou a Angra do Butim.",
			},
			["Noblegarden"] = {
				["name"] = "Jardinova",
				["description"] = "A festa de Jardinova chegou.  Os campos de testes de cada raça, o lugar onde os jovens heróis testam sua força, agora se encontram repletos de belos ovos recheados e muito bem escondidinhos.  Quantos você conseguirá encontrar?",
			},
			["MidsummerFireFestival"] = {
				["name"] = "Festival do Fogo do Solstício",
				["description"] = "É uma época de alegria e celebração, dedicada à estação mais quente do ano.",
			},
			["WintersVeil"] = {
				["name"] = "Festa do Véu de Inverno",
				["description"] = "Papai Inverno está visitando as cidades de Altaforja e Orgrimmar, cortesia da Fazenda Bosque Defumado.  Por toda Azeroth, esta é a época da alegria!",
			},
			["LoveisintheAir"] = {
				["name"] = "O Amor Está No Ar",
				["description"] = "Tem alguma coisa no ar das maiores cidades de Azeroth.  Muitos guardas e cidadãos passam os dias dando e recebendo presentes amorosos.",
			},
			["HallowsEnd"] = {
				["name"] = "Noturnália",
				["description"] = "Noturnália celebra a libertação dos Renegados do jugo do Flagelo.\r\n\r\nÉ a época de diversão e traquinagens, e os Estalajadeiros de Azeroth distribuem gostosuras e travessuras para quem pedir.",
			},
			["LunarFestival"] = {
				["name"] = "Festival da Lua",
				["description"] = "Todo ano, os druidas da Clareira da Lua celebram o triunfo de sua cidade sobre um mal ancestral. Durante o Festival da Lua, os cidadãos de Azeroth têm a oportunidade de honrar os anciãos, celebrando sua sabedoria e experiência com banquetes magníficos e, claro... soltando muitos fogos de artifício!",
			},
			["DarkmoonFaireElwynn"] = {
				["name"] = "Feira de Negraluna",
				["description"] = "A Feira de Negraluna chegou e, dessa vez, o evento acontecerá na idílica Floresta de Elwynn.\r\n\r\nVenha ver Silas Negraluna e sua trupe, divirta-se com jogos que testam a mente e os nervos e veja maravilhas exóticas vindas de todas as partes de Azeroth... e além!",
			},
			["StranglethornFishingExtravaganza"] = {
				["name"] = "Festerê de Pesca da Selva do Espinhaço",
				["description"] = "Um torneio de pesca que acontece na costa da Selva do Espinhaço.  Pesque todos os papas-finas que puder! \r\n\r\nQuem será o mestre pescador que vai papar o grande prêmio, sendo o primeiro a pescar quarenta peixes? Pode ser você!",
			},
			["ChildrensWeek"] = {
				["name"] = "Semana das Crianças",
				["description"] = "Mostre a um órfão como é a vida de um herói! Visite a Matriarca Ananéri em Ventobravo, a Matriarca Uivadora em Orgrimmar, a Matriarca Misericórdia em Shattrath ou a Matriarca Aria em Dalaran, e realize o sonho de uma criança.",
			},
		},
	},
	["ruRU"] = {
		["CalendarPVP"] = {
			["ArathiBasin"] = {
				["name"] = "К оружию! Низина Арати",
				["description"] = "Не стихают бои в Низине Арати... Вечная слава отважным воинам, сражающимся на поле брани.",
			},
			["AlteracValley"] = {
				["name"] = "К оружию! Альтеракская долина",
				["description"] = "Не стихают бои в Альтеракской долине... Вечная слава отважным воинам, сражающимся на поле брани.",
			},
			["WarsongGulch"] = {
				["name"] = "К оружию! Ущелье Песни Войны",
				["description"] = "Не стихают бои в Ущелье Песни Войны... Вечная слава отважным воинам, сражающимся на поле брани.",
			},
		},
		["CalendarHolidays"] = {
			["DarkmoonFaireMulgore"] = {
				["name"] = "Ярмарка Новолуния",
				["description"] = "К подножию Громового Утеса приехала Ярмарка Новолуния!\r\n\r\nПознакомься с Сайласом Новолунием и его труппой, испытай свою смелость и ловкость и полюбуйся роскошными видами со всего Азерота и за его пределами!",
			},
			["HarvestFestival"] = {
				["name"] = "Неделя урожая",
				["description"] = "Неделя урожая – это время вспомнить о тех, кто погиб на полях сражений, защищая друзей и союзников. Мы накрываем столы возле Стальгорна и Оргриммара, чтобы почтить память павших героев.",
			},
			["FireworksSpectacular"] = {
				["name"] = "Праздник фейерверков",
				["description"] = "Праздник Огненного солнцеворота отмечается после захода солнца.\r\n\r\nПолюбуйся роскошным фейерверком в одной из столиц Азерота или в Пиратской Бухте.",
			},
			["Noblegarden"] = {
				["name"] = "Сад чудес",
				["description"] = "По всему Азероту начинается празднование Сада чудес! Юные герои, испытайте свои силы в это волшебное время, когда в каждом укромном местечке можно отыскать яйцо с подарком. Сколько удастся найти вам?",
			},
			["MidsummerFireFestival"] = {
				["name"] = "Огненный солнцеворот",
				["description"] = "Давайте весело отметим наступление самого жаркого времени года!",
			},
			["WintersVeil"] = {
				["name"] = "Зимний Покров",
				["description"] = "Скоро в Стальгорн и Оргриммар придет Дедушка Зима. Он везет нам подарки с Пастбищ Дымного Леса! Веселись, Азерот, наступает Новый Год!",
			},
			["LoveisintheAir"] = {
				["name"] = "Любовная лихорадка",
				["description"] = "Любовная лихорадка охватила все большие города Азерота. Забыты ссоры и распри; горожане и стражи обмениваются поцелуями и подарками!",
			},
			["HallowsEnd"] = {
				["name"] = "Тыквовин",
				["description"] = "На Тыквовин мы празднуем освобождение Отрекшихся от Плети.\r\n\r\nВо всех тавернах Азерота тебя ждут шутки, смех и сладости!",
			},
			["LunarFestival"] = {
				["name"] = "Лунный фестиваль",
				["description"] = "Каждый год друиды Лунной поляны устраивают празднество по случаю великой победы над древним злом. Во время Лунного фестиваля жители Азерота посещают своих предков и приобщаются к их мудрости, от души пируют и, разумеется... запускают фейерверки!",
			},
			["DarkmoonFaireElwynn"] = {
				["name"] = "Ярмарка Новолуния",
				["description"] = "В тихий Элвиннский лес приехала Ярмарка Новолуния!\r\n\r\nПознакомься с Сайласом Новолунием и его труппой, испытай свою смелость и ловкость и полюбуйся роскошными видами со всего Азерота и за его пределами!",
			},
			["StranglethornFishingExtravaganza"] = {
				["name"] = "Рыбомания Тернистой долины",
				["description"] = "Турнир рыболовов собирает лучших мастеров в Тернистой долине. Поймай как можно больше вкуснорыб – и стань чемпионом!\r\n\r\nСможешь ли ты завоевать главный приз, быстрее всех выловив сорок блестящих рыбин?",
			},
			["ChildrensWeek"] = {
				["name"] = "Детская неделя",
				["description"] = "Покажи сиротке жизнь настоящего искателя приключений! Загляни к попечительнице сирот Найтингейл в Штормграде, к попечительнице сирот Батлвейл в Оргриммаре или к попечительнице сирот Миле в Шаттрате и исполни самые сокровенные мечты маленьких детишек!",
			},
		},
	},
	["frFR"] = {
		["CalendarHolidays"] = {
			["DarkmoonFaireMulgore"] = {
				["name"] = "Foire de Sombrelune",
				["description"] = "La foire de Sombrelune est installée au pied des Pitons du Tonnerre.\r\n\r\nRendez visite à Silas Sombrelune et sa troupe, jouez à des jeux qui mettront à l'épreuve votre esprit et vos nerfs, et découvrez des visions exotiques venues des quatre coins d'Azeroth… et au-delà !",
			},
			["HarvestFestival"] = {
				["name"] = "Fête des moissons",
				["description"] = "La fête des Moissons permet de rendre hommage à ceux qui ont sacrifié leur vie pour aider leurs amis et leurs alliés. Des festins sont organisés à Orgrimmar et Forgefer en l'honneur de ces héros disparus.",
			},
			["FireworksSpectacular"] = {
				["name"] = "Féerie des artifices",
				["description"] = "Lorsque le soleil se couche, la fin du solstice est célébrée toutes les heures par des feux d'artifice époustouflants.\r\n\r\nPour voir le spectacle, rendez-vous dans n'importe quelle capitale ou à Baie-du-Butin.",
			},
			["Noblegarden"] = {
				["name"] = "Le Jardin des nobles",
				["description"] = "La fête du Jardin des nobles est arrivée. Les terres où chaque jeune héros teste ses forces pour la première fois cachent toutes des œufs remplis de trésors. Combien arriverez-vous à en trouver ?",
			},
			["MidsummerFireFestival"] = {
				["name"] = "Fête du Feu du solstice d'été",
				["description"] = "Un moment de joie et de fête, dédié à la plus chaude saison de l'année.",
			},
			["WintersVeil"] = {
				["name"] = "Voile d'hiver",
				["description"] = "Le Grand-père Hiver se rend dans les villes de Forgefer et d'Orgrimmar, avec l'aimable autorisation des Gourmandises Fumebois. Et dans tout Azeroth, c'est la saison de la bonne humeur !",
			},
			["ChildrensWeek"] = {
				["name"] = "Semaine des enfants",
				["description"] = "Montrez à un orphelin à quoi ressemble la vie d'un héros ! Rendez visite à la directrice de l'orphelinat Rossignol à Hurlevent, à la directrice de l'orphelinat Plainteguerre à Orgrimmar, à Miss Hérikorde à Shattrath, ou à la directrice de l'orphelinat Aria à Dalaran, et réalisez les rêves d'un enfant !",
			},
			["DarkmoonFaireElwynn"] = {
				["name"] = "Foire de Sombrelune",
				["description"] = "La foire de Sombrelune est installée dans la sublime forêt d'Elwynn.\r\n\r\nRendez visite à Silas Sombrelune et sa troupe, jouez à des jeux qui mettront à l'épreuve votre esprit et vos nerfs, et découvrez des visions exotiques venues des quatre coins d'Azeroth… et au-delà !",
			},
			["LunarFestival"] = {
				["name"] = "Fête lunaire",
				["description"] = "Chaque année, les druides de Reflet-de-lune commémorent la victoire de leur cité sur un mal ancien. Pendant la fête lunaire, les habitants d’Azeroth ont l’occasion de rendre hommage à leurs anciens en écoutant leurs avis, en participant à de splendides festins et bien entendu… en tirant des feux d’artifice !",
			},
			["HallowsEnd"] = {
				["name"] = "Sanssaint",
				["description"] = "La Sanssaint célèbre la séparation entre les Réprouvés et le Fléau.\r\n\r\nLa fête et l'espièglerie règnent tandis que les aubergistes d'Azeroth distribuent bonbons et blagues à qui le leur demande.",
			},
			["StranglethornFishingExtravaganza"] = {
				["name"] = "Concours de pêche de Strangleronce",
				["description"] = "Un tournoi de pêche qui se déroule le long des côtes de la vallée de Strangleronce. Pêchez autant de courbines que possible !\r\n\r\nSerez-vous le maître pêcheur, qui, le premier, attrapera quarante poissons et gagnera le grand prix ?",
			},
			["LoveisintheAir"] = {
				["name"] = "De l'amour dans l'air",
				["description"] = "Il y a quelque chose dans l'air dans les capitales d'Azeroth. Gardes et habitants passent leurs journées à donner des cadeaux à d'autres citoyens amoureux et à en recevoir.",
			},
		},
		["CalendarPVP"] = {
			["ArathiBasin"] = {
				["name"] = "Appel aux armes : bassin Arathi",
				["description"] = "La bataille pour le bassin Arathi s'intensifie. Un plus grand honneur est donné à ceux qui prêtent allégeance à leur seigneur et qui se battent à Arathi.",
			},
			["AlteracValley"] = {
				["name"] = "Appel aux armes : vallée d'Alterac",
				["description"] = "La bataille pour la vallée d'Alterac s'intensifie. Un plus grand honneur est donné à ceux qui prêtent allégeance à leur seigneur et qui se battent à Alterac.",
			},
			["WarsongGulch"] = {
				["name"] = "Appel aux armes : goulet des Chanteguerres",
				["description"] = "La bataille pour le goulet des Chanteguerres s'intensifie. Un plus grand honneur est donné à ceux qui prêtent allégeance à leur seigneur et qui se battent dans le goulet.",
			},
		},
	},
	["koKR"] = {
		["CalendarHolidays"] = {
			["DarkmoonFaireMulgore"] = {
				["name"] = "다크문 축제",
				["description"] = "이번에는 다크문 축제가 여기, 썬더 블러프 기슭에서 열립니다. 실라스 다크문과 그 유랑단을 만나 보세요. 속마음을 점쳐보기도 하고 아제로스 구석구석에서 모인 신기한 여러 가지를 즐기실 수도 있답니다... 이게 전부가 아니니 직접 가보세요!",
			},
			["HarvestFestival"] = {
				["name"] = "추수절",
				["description"] = "추수절은 친구와 동지를 위해 목숨을 바친 이들을 기념하는 시간입니다. 오그리마와 아이언포지 외곽에는 세상을 떠난 영웅을 기리며 잔치가 벌어집니다.",
			},
			["FireworksSpectacular"] = {
				["name"] = "화려한 불꽃놀이",
				["description"] = "해가 진 후에는, 한여름의 열기를 축하하는 뜻으로 매시간 화려한 불꽃놀이가 펼쳐집니다. 불꽃놀이를 보고 싶으시면 주요 도시나 무법항을 찾아 주세요.",
			},
			["Noblegarden"] = {
				["name"] = "귀족의 정원",
				["description"] = "귀족의 정원에서 향연이 시작되었습니다. 종족마다 젊은 영웅들이 처음으로 능력을 시험받는 시험장에 교묘하게 숨겨진 보물 알이 있습니다. 몇 개나 찾을 수 있을까요?",
			},
			["MidsummerFireFestival"] = {
				["name"] = "한여름 불꽃축제",
				["description"] = "일 년 중, 가장 뜨거운 계절을 기념하여 모두가 떠들고 즐기는 시간입니다.",
			},
			["WintersVeil"] = {
				["name"] = "겨울맞이 축제",
				["description"] = "겨울 할아버지가 굴뚝나무 목장조합의 승인을 받아 오그리마와 아이언포지를 방문합니다. 아제로스 어디나 즐거움이 가득 넘쳐납니다!",
			},
			["LunarFestival"] = {
				["name"] = "달의 축제",
				["description"] = "매년 달숲 드루이드들은 고대 악을 무찌른 승리를 기념하는 축제를 엽니다. 달의 축제 기간 동안 아제로스의 시민들은 선조들의 명예와 지혜를 기리고, 즐거운 축제를 함께 즐깁니다. 물론 많은 불꽃놀이도 마음껏 즐길 수 있습니다!",
			},
			["DarkmoonFaireElwynn"] = {
				["name"] = "다크문 축제",
				["description"] = "이번에는 다크문 축제가 여기, 목가적인 풍경이 펼쳐진 엘윈 숲에서 열립니다. 실라스 다크문과 그 유랑단을 만나 보세요. 속마음을 점쳐보기도 하고 아제로스 구석구석에서 모인 신기한 여러 가지를 물건을 즐기실 수도 있답니다... 이게 전부가 아니니 직접 가보세요!",
			},
			["ChildrensWeek"] = {
				["name"] = "어린이 주간",
				["description"] = "영웅이란 어떤 삶을 사는지, 고아 어린이들에게 직접 보여주세요! 스톰윈드의 나이팅게일 보육원 원장님이나 오그리마의 배틀웨일 보육원 원장님, 샤트라스의 머시 보육원 원장님, 달라란의 아리아 보육원 원장님을 만나보시고 어린이들의 소망을 이뤄주세요.",
			},
			["HallowsEnd"] = {
				["name"] = "할로윈 축제",
				["description"] = "할로윈 축제는 포세이큰이 스컬지로부터 해방된 것을 축하하는 행사입니다. 누구든 요청하기만 하면 아제로스에 있는 여관주인들에게서 선물을 받을 수 있습니다. 그 선물이 진짜 선물일지 무언가 다른 것일지는 열어봐야 알겠지만요.",
			},
			["StranglethornFishingExtravaganza"] = {
				["name"] = "가시덤불 골짜기 낚시왕 선발대회",
				["description"] = "가시덤불 골짜기 해안을 따라 펼쳐지는 낚시대회입니다. 맛둥어를 가능한 한 많이 낚아 올리세요! 맛둥어 40마리를 먼저 낚고 우승 상품을 차지할 낚시의 대가는 과연 누구일까요?",
			},
			["LoveisintheAir"] = {
				["name"] = "온누리에 사랑을",
				["description"] = "아제로스의 주요 도시에 특별한 분위기가 감돕니다. 경비병이나 도시 주민들은 좋아하는 이와 선물을 주고받으며 이날을 보냅니다.",
			},
		},
		["CalendarPVP"] = {
			["ArathiBasin"] = {
				["name"] = "전장으로: 아라시 분지",
				["description"] = "아라시 분지에서 전투가 점점 치열해지고 있습니다. 종족을 위해 칼을 뽑아들고 아라시 분지 전투에 참여하는 이들에게는 크나큰 명예가 있을 것입니다.",
			},
			["AlteracValley"] = {
				["name"] = "전장으로: 알터랙 계곡",
				["description"] = "알터랙 계곡에서 전투가 점점 치열해지고 있습니다. 종족을 위해 칼을 뽑아들고 알터랙 전투에 참여하는 이들에게는 크나큰 명예가 있을 것입니다.",
			},
			["WarsongGulch"] = {
				["name"] = "전장으로: 전쟁노래 협곡",
				["description"] = "전쟁노래 협곡에서 전투가 점점 치열해지고 있습니다. 종족을 위해 칼을 뽑아들고 전쟁노래 협곡 전투에 참여하는 이들에게는 크나큰 명예가 있을 것입니다.",
			},
		},
	},
	["esMX"] = {
		["CalendarHolidays"] = {
			["DarkmoonFaireMulgore"] = {
				["name"] = "Feria de la Luna Negra",
				["description"] = "La Feria de la Luna Negra está aquí y ahora, al pie de la Cima del Trueno.\r\n\r\nConoce a Silas Luna Negra y a su compañía, diviértete con juegos que ponen a prueba tu mente y tu nervio, y contempla vistas exóticas de todos los rincones de Azeroth... ¡y más allá!",
			},
			["HarvestFestival"] = {
				["name"] = "Festival de la Cosecha",
				["description"] = "El Festival de la Cosecha es una ocasión para rendir un homenaje a aquellos que han sacrificado su vida para ayudar a sus amigos y aliados. A las afueras de Orgrimmar y Forjaz se dan banquetes en honor a estos héroes caídos.",
			},
			["FireworksSpectacular"] = {
				["name"] = "Espectáculo de fuegos artificiales",
				["description"] = "Cuando el sol se pone, se celebra el final del solsticio de verano con un gran espectáculo de fuegos artificiales cada hora.\r\n\r\nPara verlo, visita cualquier capital o Bahía del Botín.",
			},
			["Noblegarden"] = {
				["name"] = "Jardín Noble",
				["description"] = "La celebración del Jardín Noble ya está aquí. Los terrenos de pruebas de cada raza, el lugar donde los jóvenes héroes demuestran su fuerza por primera vez, esconden con ingenio pequeños huevos ocultos. ¿Cuántos eres capaz de encontrar?",
			},
			["MidsummerFireFestival"] = {
				["name"] = "Festival de Fuego del Solsticio de Verano",
				["description"] = "Una época de alegría y celebración dedicada a la estación más calurosa del año.",
			},
			["WintersVeil"] = {
				["name"] = "El festín del Festival de Invierno",
				["description"] = "El Gran Padre Invierno está visitando las ciudades de Forjaz y Orgrimmar, por cortesía de los Pastos de Bosquehumeante. Y por todo Azeroth ¡es la temporada de la alegría!",
			},
			["ChildrensWeek"] = {
				["name"] = "Semana de los Niños",
				["description"] = "¡Enséñale a un niño huérfano cómo es la vida de un héroe! Ve a ver a la supervisora de huérfanos Ruiseñor en Ventormenta, a la supervisora de huérfanos Llantobatalla en Orgrimmar, a la supervisora de huérfanos Piedad en Shattrath o a la supervisora de huérfanos Aria en Dalaran y haz realidad el sueño de un niño.",
			},
			["DarkmoonFaireElwynn"] = {
				["name"] = "Feria de la Luna Negra",
				["description"] = "La Feria de la Luna Negra ya está aquí, en el idílico Bosque de Elwynn.\r\n\r\nConoce a Silas Luna Negra y a su compañía, diviértete con juegos que ponen a prueba tu mente y tu nervio, y contempla vistas exóticas de todos los rincones de Azeroth... ¡y más allá!",
			},
			["LunarFestival"] = {
				["name"] = "Festival Lunar",
				["description"] = "Cada año los druidas de Claro de la Luna celebran el gran triunfo de su ciudad sobre un antiguo mal. Durante el Festival Lunar los ciudadanos de Azeroth tienen la oportunidad de rendir honor a sus ancestros celebrando su sabiduría con magníficos festines y, por supuesto, ¡lanzando fuegos artificiales!",
			},
			["HallowsEnd"] = {
				["name"] = "Halloween",
				["description"] = "Halloween celebra la separación de los Renegados de la Plaga.\r\n\r\nLa diversión y las travesuras reinan por doquier, mientras los taberneros de Azeroth hacen truco o trato a cualquiera que se lo pida.",
			},
			["StranglethornFishingExtravaganza"] = {
				["name"] = "Gran espectáculo de pesca de Tuercespina",
				["description"] = "Torneo de pesca, que se celebra por las costas de Vega de Tuercespina. ¡Captura todo el pezrico que puedas! \r\n\r\n¿Serás tú el primer gran pescador que capture cuarenta peces y se lleve el gran premio?",
			},
			["LoveisintheAir"] = {
				["name"] = "Amor en el aire",
				["description"] = "Algo flota en el aire de las grandes ciudades de Azeroth. Numerosos guardias y ciudadanos pasan unos días intercambiando regalos con otros amorosos vecinos.",
			},
		},
		["CalendarPVP"] = {
			["ArathiBasin"] = {
				["name"] = "Llamamiento a las armas: Cuenca de Arathi",
				["description"] = "La batalla por la Cuenca de Arathi se hace cada vez más intensa. A aquellos que ofrecen la espada en nombre de su Señor y batallan en Arathi se les reconoce gran honra.",
			},
			["AlteracValley"] = {
				["name"] = "Llamamiento a las armas: Valle de Alterac",
				["description"] = "La batalla por el Valle de Alterac se hace cada vez más intensa. A aquellos que ofrecen la espada en nombre de su Señor y batallan en Alterac se les reconoce gran honra.",
			},
			["WarsongGulch"] = {
				["name"] = "Llamamiento a las armas: Garganta Grito de Guerra",
				["description"] = "La batalla por la Garganta Grito de Guerra se hace cada vez más intensa. A aquellos que ofrecen la espada en nombre de su Señor y batallan en la Garganta Grito de Guerra se les reconoce gran honra.",
			},
		},
	},
	["enUS"] = {
		["CalendarPVP"] = {
			["ArathiBasin"] = {
				["name"] = "Call to Arms: Arathi Basin",
				["description"] = "The battle for Arathi Basin grows intense.  Greater honor is given to those who pledge sword to their liege and battle in Arathi.",
			},
			["AlteracValley"] = {
				["name"] = "Call to Arms: Alterac Valley",
				["description"] = "The battle for Alterac Valley grows intense.  Greater honor is given to those who pledge sword to their liege and battle in Alterac.",
			},
			["WarsongGulch"] = {
				["name"] = "Call to Arms: Warsong Gulch",
				["description"] = "The battle for Warsong Gulch grows intense.  Greater honor is given to those who pledge sword to their liege and battle in the Gulch.",
			},
		},
		["CalendarHolidays"] = {
			["DarkmoonFaireMulgore"] = {
				["name"] = "Darkmoon Faire",
				["description"] = "The Darkmoon Faire is here, this time at the foot of Thunder Bluff.\r\n\r\nMeet Silas Darkmoon and his troupe, play games that test mind and nerve, and behold exotic sights from the four corners of Azeroth... and beyond!",
			},
			["HarvestFestival"] = {
				["name"] = "Harvest Festival",
				["description"] = "The Harvest Festival is a time to commemorate those  who have sacrificed their lives to help friends and allies.  Feasts are held outside Orgrimmar and Ironforge in honor of these fallen heroes.",
			},
			["FireworksSpectacular"] = {
				["name"] = "Fireworks Spectacular",
				["description"] = "After the sun sets, the end of Midsummer is celebrated, with an hourly firework extravaganza.\r\n\r\nTo watch the show, visit any capital city or Booty Bay.",
			},
			["Noblegarden"] = {
				["name"] = "Noblegarden",
				["description"] = "The feast of Noblegarden has arrived.  The proving grounds of each race, the place where young heroes first test their strength, each holds cleverly hidden treasure eggs.  How many can you find?",
			},
			["MidsummerFireFestival"] = {
				["name"] = "Midsummer Fire Festival",
				["description"] = "A time of merriment and celebration, dedicated to the hottest season of the year.",
			},
			["WintersVeil"] = {
				["name"] = "Feast of Winter Veil",
				["description"] = "Greatfather Winter is visiting the cities of Ironforge and Orgrimmar, courtesy of Smokywood Pastures.  And throughout Azeroth, it is the season to be jolly!",
			},
			["LoveisintheAir"] = {
				["name"] = "Love is in the Air",
				["description"] = "Something is in the air in the major cities of Azeroth.  Many guards and townsfolk spend their days giving and receiving gifts to other amorous citizens.",
			},
			["HallowsEnd"] = {
				["name"] = "Hallow's End",
				["description"] = "Hallow's End celebrates the break of the Forsaken from the Scourge.\r\n\r\nFun and mischief reign as the Innkeepers of Azeroth give treats, and tricks, to whomever asks.",
			},
			["ChildrensWeek"] = {
				["name"] = "Children's Week",
				["description"] = "Show an orphan what the hero's life is like!  Visit Orphan Matron Nightingale in Stormwind, Orphan Matron Battlewail in Orgrimmar, Orphan Matron Mercy in Shattrath, or Orphan Matron Aria in Dalaran and make a child's dream come true.",
			},
			["DarkmoonFaireElwynn"] = {
				["name"] = "Darkmoon Faire",
				["description"] = "The Darkmoon Faire is here, this time in idyllic Elwynn Forest.\r\n\r\nMeet Silas Darkmoon and his troupe, play games that test mind and nerve, and behold exotic sights from the four corners of Azeroth... and beyond!",
			},
			["StranglethornFishingExtravaganza"] = {
				["name"] = "Stranglethorn Fishing Extravaganza",
				["description"] = "A fishing tournament, competed along the coasts of Stranglethorn Vale.  Catch as many tastyfish as you can!  \r\n\r\nWill you be the master fisherman who catches forty fish first and wins the grand prize?",
			},
			["LunarFestival"] = {
				["name"] = "Lunar Festival",
				["description"] = "Every year the druids of Moonglade hold a celebration of their city's great triumph over an ancient evil. During the Lunar Festival, citizens of Azeroth have the opportunity to honor their elders by celebrating their sage wisdom, sharing in magnificent feasts, and of course... shooting lots of fireworks!",
			},
		},
	},
	["deDE"] = {
		["CalendarHolidays"] = {
			["DarkmoonFaireMulgore"] = {
				["name"] = "Dunkelmond-Jahrmarkt",
				["description"] = "Der Dunkelmond-Jahrmarkt ist hier, diesmal am Fuße von Donnerfels.\r\n\r\nTrefft Silas Dunkelmond und seine Truppe, spielt Spiele, die Kopf und Nerven auf die Probe stellen und bewundert exotische Anblicke aus allen Himmelsrichtungen Azeroths... und darüber hinaus!",
			},
			["HarvestFestival"] = {
				["name"] = "Erntedankfest",
				["description"] = "Das Erntedankfest ist die Zeit, jenen zu gedenken, die ihr Leben opferten, um Freunden und Familie zu helfen. Feste werden vor den Toren von Orgrimmar und Eisenschmiede abgehalten, um die gefallenen Helden zu ehren.",
			},
			["FireworksSpectacular"] = {
				["name"] = "Feuerwerksspektakel",
				["description"] = "Nach Sonnenuntergang wird das Ende der Sonnenwende mit einem stündlichen Feuerwerk gefeiert.\r\n\r\nBegebt Euch in eine der Hauptstädte oder nach Beutebucht, um das Spektakel zu sehen.",
			},
			["Noblegarden"] = {
				["name"] = "Nobelgartenfest",
				["description"] = "Das Nobelgartenfest ist da. Die Zeit für jedes Volk, sich zu beweisen, wenn junge Helden zum ersten Mal ihre Stärke testen und nach clever versteckten Schatzeiern suchen. Wie viele könnt Ihr finden?",
			},
			["MidsummerFireFestival"] = {
				["name"] = "Sonnenwendfest",
				["description"] = "Eine Zeit der Fröhlichkeit und des Feierns, die der heißesten Jahreszeit gewidmet ist.",
			},
			["WintersVeil"] = {
				["name"] = "Winterhauchfest",
				["description"] = "Großvater Winter besucht mit freundlicher Unterstützung von Kokelwälder die Städte Eisenschmiede und Orgrimmar und in ganz Azeroth bricht eine fröhliche Jahreszeit an!",
			},
			["LunarFestival"] = {
				["name"] = "Mondfest",
				["description"] = "Jedes Jahr veranstalten die Druiden der Mondlichtung ein Fest zu Ehren des großen Sieges ihrer Stadt über ein uraltes Unheil. Während des Mondfestes erhalten die Bewohner Azeroths die Gelegenheit, ihre Ältesten zu ehren, indem sie ihre Weisheit feiern, Festmahle miteinander teilen und natürlich... Feuerwerkskörper zünden!",
			},
			["DarkmoonFaireElwynn"] = {
				["name"] = "Dunkelmond-Jahrmarkt",
				["description"] = "Der Dunkelmond-Jahrmarkt ist hier, diesmal im Wald von Elwynn.\r\n\r\nTrefft Silas Dunkelmond und seine Truppe, spielt Spiele, die Kopf und Nerven auf die Probe stellen und bewundert exotische Anblicke aus allen Himmelsrichtungen Azeroths... und darüber hinaus!",
			},
			["ChildrensWeek"] = {
				["name"] = "Kinderwoche",
				["description"] = "Zeigt einem Waisenkind, wie das Leben eines Helden aussieht! Besucht Waisenmatrone Nachtigall in Sturmwind, Waisenmatrone Schlachterbe in Orgrimmar, Waisenmatrone Gnädig in Shattrath oder Waisenmatrone Aria in Dalaran und lasst den Traum eines Kindes in Erfüllung gehen.",
			},
			["HallowsEnd"] = {
				["name"] = "Schlotternächte",
				["description"] = "In den Schlotternächten wird die Abspaltung der Verlassenen von der Geißel gefeiert.\r\n\r\nSpaß und Unsinn regieren, wenn die Gastwirte Azeroths Süßes und Saures an alle verteilen, die danach fragen.",
			},
			["StranglethornFishingExtravaganza"] = {
				["name"] = "Anglerwettbewerb im Schlingendorntal",
				["description"] = "Ein Angelturnier, das an der Küste des Schlingendorntals abgehalten wird. Fangt so viele Leckerfische, wie Ihr nur könnt!\r\n\r\nWerdet Ihr der Meisterangler, der am schnellsten vierzig Fische fängt und den großen Preis gewinnt?",
			},
			["LoveisintheAir"] = {
				["name"] = "Liebe liegt in der Luft",
				["description"] = "In den großen Städten Azeroths liegt etwas in der Luft. Viele Wachen und Einwohner verbringen Tage damit, Geschenke an andere verliebte Bürger zu verteilen oder solche zu erhalten.",
			},
		},
		["CalendarPVP"] = {
			["ArathiBasin"] = {
				["name"] = "Zu den Waffen: Arathibecken",
				["description"] = "Der Kampf um das Arathibecken wird hitziger. Große Ehre wartet auf diejenigen, die für ihren Herren in die Schlacht um Arathi ziehen.",
			},
			["AlteracValley"] = {
				["name"] = "Zu den Waffen: Alteractal",
				["description"] = "Der Kampf um das Alteractal wird hitziger. Große Ehre wartet auf diejenigen, die für ihren Herren in die Schlacht um Alterac ziehen.",
			},
			["WarsongGulch"] = {
				["name"] = "Zu den Waffen: Kriegshymnenschlucht",
				["description"] = "Der Kampf um die Kriegshymnenschlucht wird hitziger. Große Ehre wartet auf diejenigen, die für ihren Herren in die Schlacht um das die Schlucht ziehen.",
			},
		},
	},
	["esES"] = {
		["CalendarPVP"] = {
			["ArathiBasin"] = {
				["name"] = "Llamamiento a las armas: Cuenca de Arathi",
				["description"] = "La batalla por la Cuenca de Arathi se hace cada vez más intensa. A aquellos que ofrecen la espada en nombre de su Señor y batallan en Arathi se les reconoce gran honra.",
			},
			["AlteracValley"] = {
				["name"] = "Llamamiento a las armas: Valle de Alterac",
				["description"] = "La batalla por el Valle de Alterac se hace cada vez más intensa. A aquellos que ofrecen la espada en nombre de su Señor y batallan en Alterac se les reconoce gran honra.",
			},
			["WarsongGulch"] = {
				["name"] = "Llamamiento a las armas: Garganta Grito de Guerra",
				["description"] = "La batalla por la Garganta Grito de Guerra se hace cada vez más intensa. A aquellos que ofrecen la espada en nombre de su Señor y batallan en la Garganta Grito de Guerra se les reconoce gran honra.",
			},
		},
		["CalendarHolidays"] = {
			["DarkmoonFaireMulgore"] = {
				["name"] = "Feria de la Luna Negra",
				["description"] = "La Feria de la Luna Negra está aquí y ahora, al pie de la Cima del Trueno.\r\n\r\nConoce a Silas Lunanegra y a su compañía, diviértete con juegos que ponen a prueba tu mente y tu nervio, y contempla vistas exóticas de todos los rincones de Azeroth... ¡y más allá!",
			},
			["HarvestFestival"] = {
				["name"] = "Festival de la Cosecha",
				["description"] = "El Festival de la Cosecha es una ocasión para rendir un homenaje a aquellos que han sacrificado su vida para ayudar a sus amigos y aliados. A las afueras de Orgrimmar y Forjaz se dan banquetes en honor a estos héroes caídos.",
			},
			["FireworksSpectacular"] = {
				["name"] = "Espectáculo de fuegos artificiales",
				["description"] = "Cuando el sol se pone, se celebra el final del solsticio de verano con un gran espectáculo de fuegos artificiales cada hora.\r\n\r\nPara verlo, visita cualquier capital o Bahía del Botín.",
			},
			["Noblegarden"] = {
				["name"] = "Jardín Noble",
				["description"] = "La celebración del Jardín Noble ya está aquí. Los terrenos de pruebas de cada raza, el lugar donde los jóvenes héroes demuestran su fuerza por primera vez, esconden con ingenio pequeños huevos ocultos. ¿Cuántos eres capaz de encontrar?",
			},
			["MidsummerFireFestival"] = {
				["name"] = "Festival de Fuego del Solsticio de Verano",
				["description"] = "Una época de alegría y celebración dedicada a la estación más calurosa del año.",
			},
			["WintersVeil"] = {
				["name"] = "El festín del Festival de Invierno",
				["description"] = "El Gran Padre Invierno está visitando las ciudades de Forjaz y Orgrimmar, por cortesía de los Pastos de Bosquehumeante. Y por todo Azeroth ¡es la temporada de la alegría!",
			},
			["LoveisintheAir"] = {
				["name"] = "Amor en el aire",
				["description"] = "Algo flota en el aire de las grandes ciudades de Azeroth. Numerosos guardias y ciudadanos pasan unos días intercambiando regalos con otros amorosos vecinos.",
			},
			["HallowsEnd"] = {
				["name"] = "Halloween",
				["description"] = "Halloween celebra la separación de los Renegados de la Plaga.\r\n\r\nLa diversión y las travesuras reinan por doquier, mientras los taberneros de Azeroth hacen truco o trato a cualquiera que se lo pida.",
			},
			["ChildrensWeek"] = {
				["name"] = "Semana de los Niños",
				["description"] = "¡Enséñale a un niño huérfano cómo es la vida de un héroe! Ve a ver a la supervisora de huérfanos Ruiseñor en Ventormenta, a la supervisora de huérfanos Llantobatalla en Orgrimmar, a la supervisora de huérfanos Piedad en Shattrath o a la supervisora de huérfanos Aria en Dalaran y haz realidad el sueño de un niño.",
			},
			["DarkmoonFaireElwynn"] = {
				["name"] = "Feria de la Luna Negra",
				["description"] = "La Feria de la Luna Negra ya está aquí, en el idílico Bosque de Elwynn.\r\n\r\nConoce a Silas Lunanegra y a su compañía, diviértete con juegos que ponen a prueba tu mente y tu nervio, y contempla vistas exóticas de todos los rincones de Azeroth... ¡y más allá!",
			},
			["StranglethornFishingExtravaganza"] = {
				["name"] = "Gran espectáculo de pesca de Tuercespina",
				["description"] = "Torneo de pesca, que se celebra por las costas de Vega de Tuercespina. ¡Captura todo el pezrico que puedas! \r\n\r\n¿Serás tú el primer gran pescador que capture cuarenta peces y se lleve el gran premio?",
			},
			["LunarFestival"] = {
				["name"] = "Festival Lunar",
				["description"] = "Cada año los druidas del Claro de la Luna celebran el gran triunfo de su ciudad sobre un antiguo mal. Durante el Festival Lunar, los ciudadanos de Azeroth tienen la oportunidad de rendir tributo a sus ancestros y celebrar su sabiduría mediante magníficos festines y, por supuesto..., ¡disparando montones de fuegos artificiales!",
			},
		},
	},
	["zhTW"] = {
		["CalendarPVP"] = {
			["ArathiBasin"] = {
				["name"] = "戰鬥的號角:阿拉希盆地",
				["description"] = "阿拉希盆地的戰鬥轉趨激烈。願意持劍投身阿拉希戰鬥的人將會獲得更大的榮譽。",
			},
			["AlteracValley"] = {
				["name"] = "戰鬥的號角:奧特蘭克山谷",
				["description"] = "奧特蘭克山谷的戰鬥轉趨激烈。願意持劍投身奧特蘭克戰鬥的人將會獲得更大的榮譽。",
			},
			["WarsongGulch"] = {
				["name"] = "戰鬥的號角:戰歌峽谷",
				["description"] = "戰歌峽谷的戰鬥轉趨激烈。願意持劍投身戰歌峽谷戰鬥的人將會獲得更大的榮譽。",
			},
		},
		["CalendarHolidays"] = {
			["DarkmoonFaireMulgore"] = {
				["name"] = "暗月馬戲團",
				["description"] = "暗月馬戲團來了，就在雷霆崖的山腳下。\r\n\r\n快來看看希拉斯·暗月和他的戲團，參與一些考驗智慧與膽量的遊戲，目睹來自艾澤拉斯各地的驚奇景象…以及更多新奇的事物在此等著你!",
			},
			["HarvestFestival"] = {
				["name"] = "收穫節",
				["description"] = "收穫節是紀念那些為了朋友與同伴犧牲生命的勇士。慶典在奧格瑪與鐵爐堡的郊外舉行，以紀念那些死去的英雄。",
			},
			["FireworksSpectacular"] = {
				["name"] = "壯麗的煙火大會",
				["description"] = "在仲夏的最後一天，日落之後大肆慶祝，接連好幾個小時的煙火大會。\r\n\r\n想要參觀表演的話，請前往各大主城或藏寶海灣。",
			},
			["Noblegarden"] = {
				["name"] = "貴族花園",
				["description"] = "貴族花園的慶典已經來嘍。這是屬於所有種族的場合，年輕的英雄們在此初試啼聲，尋找被巧妙收藏的藏寶蛋。你找到了幾個呢?",
			},
			["MidsummerFireFestival"] = {
				["name"] = "仲夏火焰節慶",
				["description"] = "歡樂與慶祝的時間，獻給一年之中最炎熱的季節。",
			},
			["WintersVeil"] = {
				["name"] = "冬幕節",
				["description"] = "冬天爺爺來拜訪鐵爐堡與奧格瑪了，還有燻木農場的禮物。在艾澤拉斯各地，這都是個充滿歡樂的季節!",
			},
			["LoveisintheAir"] = {
				["name"] = "愛就在身邊",
				["description"] = "艾澤拉斯的主城中瀰漫著不同的氣氛。許多守衛與平民會在這段期間內與其愛慕的對象互贈禮物。",
			},
			["HallowsEnd"] = {
				["name"] = "萬鬼節",
				["description"] = "萬鬼節是為了慶祝被遺忘者掙脫天譴軍團的束縛。\r\n\r\n歡笑與惡作劇在各地上演，艾澤拉斯各地的旅店主人提供給每個人小糖果與惡作劇道具。",
			},
			["ChildrensWeek"] = {
				["name"] = "兒童週",
				["description"] = "讓一個孤兒瞧瞧英雄的日常生活!去拜訪暴風城的孤兒監護員南丁格爾或奧格瑪的孤兒監護員巴特維爾，並且讓一個孩子美夢成真。",
			},
			["DarkmoonFaireElwynn"] = {
				["name"] = "暗月馬戲團",
				["description"] = "暗月馬戲團來了，就在田園般的艾爾文森林中。\r\n\r\n快來看看希拉斯·暗月和他的戲團，參與一些考驗智慧與膽量的遊戲，目睹來自艾澤拉斯各地的驚奇景象…以及更多新奇的事物在此等著你!",
			},
			["StranglethornFishingExtravaganza"] = {
				["name"] = "荊棘谷釣魚大賽",
				["description"] = "一場在荊棘谷的海岸舉辦的釣魚大賽。看你能釣起多少美味的魚!\r\n\r\n你會是最先釣起四十隻魚的釣魚大師，並且贏得大獎嗎?",
			},
			["LunarFestival"] = {
				["name"] = "新年慶典",
				["description"] = "每年月光林地的德魯伊們都會舉辦一場歡慶他們擊敗一個古老魔物的祭典。在新年節慶期間內，艾澤拉斯的居民們可以趁此佳節來榮耀他們的長者，藉由歌頌他們的智慧，舉辦盛宴，當然還有...數不盡的煙火!",
			},
		},
	},
	["zhCN"] = {
		["CalendarPVP"] = {
			["ArathiBasin"] = {
				["name"] = "战斗的召唤：阿拉希盆地",
				["description"] = "阿拉希盆地的战斗愈发激烈。在阿拉希盆地浴血奋战的勇士们必将载誉而归。",
			},
			["AlteracValley"] = {
				["name"] = "战斗的召唤：奥特兰克山谷",
				["description"] = "奥特兰克山谷的战斗愈发激烈。在奥特兰克山谷浴血奋战的勇士们必将载誉而归。",
			},
			["WarsongGulch"] = {
				["name"] = "战斗的召唤：战歌峡谷",
				["description"] = "战歌峡谷的战斗愈发激烈。在战歌峡谷浴血奋战的勇士们必将载誉而归。",
			},
		},
		["CalendarHolidays"] = {
			["DarkmoonFaireMulgore"] = {
				["name"] = "暗月马戏团",
				["description"] = "这一次，暗月马戏团来到了雷霆崖的脚下。\r\n\r\n去拜访希拉斯·暗月和他的马戏团，玩一玩考验头脑和胆量的游戏，看一看来自艾泽拉斯各地的奇特珍品……还有更多的乐趣在等着你！",
			},
			["HarvestFestival"] = {
				["name"] = "收获节",
				["description"] = "收获节的意义，在于纪念那些为帮助朋友和伙伴而牺牲的英雄们。奥格瑞玛和铁炉堡外都在举行盛宴，向那些英雄表示敬意。",
			},
			["FireworksSpectacular"] = {
				["name"] = "焰火表演",
				["description"] = "在日落之后，伴随着每小时一次的焰火舞会，仲夏火焰节将缓缓落下帷幕。\r\n\r\n想要观看表演的话，可以前去各大主城或者藏宝海湾。",
			},
			["Noblegarden"] = {
				["name"] = "复活节",
				["description"] = "复活节到了。许多彩蛋巧妙地隐藏在每个种族的新手区域——年轻的英雄们初次检验自己力量的地方，你能找到多少呢？",
			},
			["MidsummerFireFestival"] = {
				["name"] = "仲夏火焰节",
				["description"] = "一个欢笑与庆祝的时刻，以纪念一年中最热的季节。",
			},
			["WintersVeil"] = {
				["name"] = "冬幕节",
				["description"] = "冬天爷爷正在带着烟林牧场的礼物访问铁炉堡和奥格瑞玛。整个艾泽拉斯到处充满着节日的喜庆气氛！",
			},
			["HallowsEnd"] = {
				["name"] = "万圣节",
				["description"] = "万圣节是被遗忘者庆祝自己摆脱天灾军团控制的节日。\r\n\r\n艾泽拉斯的旅店老板们会向所有上门问候的人送出糖果或恶作剧，到处都是欢乐的笑声。",
			},
			["LoveisintheAir"] = {
				["name"] = "情人节",
				["description"] = "艾泽拉斯的各大主城中，弥漫着浪漫温馨的气息。卫兵与市民们正在忙碌地送出和收到各种代表倾慕之情的礼物。",
			},
			["LunarFestival"] = {
				["name"] = "春节",
				["description"] = "月光林地的德鲁伊每年都会举行一次庆典，以庆祝他们对一股远古的邪恶力量所取得的胜利。在春节期间，艾泽拉斯的人民可以祭拜睿智的祖先，共享美味的盛宴，还有……数不清的绚丽的烟花！",
			},
			["DarkmoonFaireElwynn"] = {
				["name"] = "暗月马戏团",
				["description"] = "这一次，暗月马戏团来到了风景如画的艾尔文森林。\r\n\r\n去拜访希拉斯·暗月和他的马戏团，玩一玩考验头脑和胆量的游戏，看一看来自艾泽拉斯各地的奇特珍品……还有更多的乐趣在等着你！",
			},
			["StranglethornFishingExtravaganza"] = {
				["name"] = "荆棘谷钓鱼大赛",
				["description"] = "在荆棘谷沿岸举行的钓鱼大赛。钓到尽可能多的可口鱼！\r\n\r\n你会不会成为第一个钓到40条鱼、赢得大奖的钓鱼大师呢？",
			},
			["ChildrensWeek"] = {
				["name"] = "儿童周",
				["description"] = "让孤儿看看英雄的生活是怎样的！拜访暴风城的孤儿监护员奈丁加尔，奥格瑞玛的孤儿监护员巴特维尔，或是沙塔斯城的孤儿院长莫希。让孩子们梦想成真吧！",
			},
		},
	},
}
